license = "MIT"
issueTrackerURL = "https://github.com/spacemex/SpaceTS/issues"

[[mods]]
modId = "space-ts"
version = "${version}"
displayName = "SpaceTs"
authors = "Space_mex"

displayURL = "https://github.com/spacemex/SpaceTS/"
# logoFile = "icon.png"
# credits = ""

description = '''
Adds Typescript support to Minecraft!
'''

#[[mixins]]
#config = "example-mod.mixins.json"

[[dependencies.space-ts]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.0.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.space-ts]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"